//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SobolevPP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Затраты
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Затраты()
        {
            this.Отчет = new HashSet<Отчет>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> Дата { get; set; }
        public string Описание { get; set; }
        public Nullable<decimal> Сумма { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Отчет> Отчет { get; set; }
    }
}
