//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SobolevPP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Отчет
    {
        public int id { get; set; }
        public Nullable<int> id_оплаты { get; set; }
        public Nullable<int> id_зарплаты { get; set; }
        public Nullable<int> id_затрат { get; set; }
    
        public virtual Зарплата Зарплата { get; set; }
        public virtual Затраты Затраты { get; set; }
        public virtual Оплаты Оплаты { get; set; }
    }
}
